# Generated by Django 4.2.3 on 2023-09-13 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('reps', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('predicted_weight', models.FloatField()),
                ('actual_weight', models.FloatField()),
                ('feedback', models.IntegerField(choices=[(-1, 'Too light'), (0, 'Just right'), (1, 'Too heavy')])),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercise', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('sets', models.IntegerField()),
                ('reps_per_set', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
